### PR TITLE
I suggest bumping to 5.x for clarity for people looking to install

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
(you can keep 4.7 too but since it's no longer recommended due to security .... maybe time to move on)

**Comment by JoeMurray** [comment]
@edsel pls proceed with this

**Comment by Edzelopez** [comment]
Thanks for the suggestion @eileenmcnaughton !

**Comment by monishdeb** [comment]
FYI added 4.7 along with 5.0

**Comment by eileenmcnaughton** [comment]
@monishdeb it's a bit academic but I've been removing 4.7 from my extensions & incrementing the version fairly steadily. (e.g the next release of extended reports will be 5.5+ but people on earlier versions can still use older releases)

 I feel like as a maintainer it's easier just to have a narrow range of versions I'm working against & by having different releases work against different Civi versions people still have a the version that works for them but if they want the latest of my extensions they need to update.

**Pull request merged**
