### PR TITLE
Add ability to add line items to line item edit

### PR DESCRIPTION
**Pull request by monishdeb**
https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/issues/6

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
I've found three bugs. 
**Blank line item created from original "total amount" entry.**
To replicate:
* Record a new contribution through the UI, leaving the "total amount" blank and save.
selection_488
* When you edit the contribution again, a line item was creating of $0 for the blank value.  

*Expected Result*
No line item created for the "total amount".  From a UI perspective, the field should ideally be hidden (like choosing a price set).

**First line item is overwritten with the total amount**
This seems to be related.  If you open a contribution with multiple line items and add a new line item, on save, the first line item will be overwritten with the contribution's total amount.  If you click "edit" and save again without making changes, you'll see the contribution total amount will change.

**Total amount can be wrong**
I imported this contribution:
```
$call = json_decode('{"GiftId":"5415","net_amount":"17116.34","contact_id":"9096","payment_instrument_id":"6","receive_date":"1925/01/01","custom_14":"1","total_amount":"17116.34","custom_16":"234","custom_17":"1","financial_type_id":"1","line_items":[{"line_item":{"0":{"line_total":"5705.44","FundId":"234","entity_table":"civicrm_contribution","qty":1,"price_field_id":1,"price_field_value_id":1,"unit_price":"5705.44"}}},{"line_item":{"1":{"line_total":"11410.90","FundId":"1386","entity_table":"civicrm_contribution","qty":1,"price_field_id":1,"price_field_value_id":2,"unit_price":"11410.90"}}}]}', true);
civicrm_api3('Order', 'create', $call);
```
My total amount displays as $17:
selection_489

**Comment by JoeMurray** [comment]
Monish will be addressing these within next day or two.

**Comment by monishdeb** [comment]
@MegaphoneJon thanks for your feedback. I have fixed the issues you have mentioned and here's the screencast for each:
1. On clicking 'Add lineitem' link it hides the rest of the element like price set. 

Without price-set:
test-multiple-before

With price-set:
test-multiple-before

2. Earlier due to the presence of thousand separator the calculated total amount was incorrect. I have fixed it and here's the screencast:
test-multiple-before

**Comment by monishdeb** [comment]
@MegaphoneJon did you get any chance to review my fixes?

**Comment by MegaphoneJon** [comment]
Not yet @monishdeb - probably tomorrow.

**Comment by MegaphoneJon** [comment]
Hi @monishdeb - here are my latest observations:
When I edit an existing contribution with line items, I get this message twice:
```
    Notice: Undefined index: label in CRM_Lineitemedit_Util::getLineItemTableInfo() (line 62 of /home/jon/local/agbu/htdocs/sites/all/civicrm/extensions/biz.jmaconsulting.lineitemedit/CRM/Lineitemedit/Util.php).
    Notice: Undefined index: label in CRM_Lineitemedit_Util::getLineItemTableInfo() (line 62 of /home/jon/local/agbu/htdocs/sites/all/civicrm/extensions/biz.jmaconsulting.lineitemedit/CRM/Lineitemedit/Util.php).
```
Note that the notices are suppressed if you open the "Edit Contribution" form in a modal.

* The bug listed above, "Blank line item created from original "total amount" entry" is now fixed.
* "Total amount can be wrong" is also fixed.
* The second bug, "First line item is overwritten with the total amount" is NOT fixed.  The UI doesn't match what I'm seeing for you - possibly in part because I'm editing an existing contribution.

See attached GIF where I open a gift, save without making any changes, and reopen.  I see the following issues:
* The first time I open the gift, line item 1 is $5705.44.  The second time, it's $17116.34.
* The "Add another item" link is present even though I didn't change anything.

Also - let me know if this is in part due to how my price set is configured.  The price set I'm using for importing has `is_quick_config` set to true, so maybe Civi thinks that this isn't using a price set?

**Comment by MegaphoneJon** [comment]
Oops, forgot the GIF:
line item bug

**Comment by monishdeb** [comment]
Hi @MegaphoneJon I have fixed the following issue:
1. Notice error (although I wasn't able to replicate it in my local on new form not in modal)
2. On simple save of 'Edit Contribution' first line-item is not overwritten now with total amount. 
3. "The "Add another item" link is present even though I didn't change anything." This is not a bug but a expected behaviour where we are providing the staff to always add additional line-item on New/Edit backoffice form. That link provides the ability to add additional line-item as per spec.

Regarding your other question:

> Also - let me know if this is in part due to how my price set is configured. The price set I'm using for importing has is_quick_config set to true, so maybe Civi thinks that this isn't using a price set?

Yes this how price-set are distinguished in Civi, via UI all those price-set which are created from 'Manage Page Set' >> 'Add Price set' has is_quick_config = FALSE. But those which are configured via online contribution page/event or those which are reserved has is_quick_config = TRUE. Based on this criteria line-editor distinguish the price-set like Civi does.

**Comment by MegaphoneJon** [comment]
I confirm that items 1 and 2 from your last item are fixed.  With regard to item 3, the issue is one of UX.  See screenshot:
selection_507

Both the form elements that I've pointed out in the screenshot do the same thing.  Note that this does NOT happen when creating a new contribution, only when editing an existing contribution.  To maintain the same UX for both creating new and editing existing contributions, I think the dropdown next to the total amount shouldn't appear.

That said, this is looking very good compared to last week!  I feel this is ready for the client to QA.  I'll put it in front of them tomorrow, and hopefully we're in the final stretch on this.

**Comment by monishdeb** [comment]
Ah ok, so that form element 'Add item' is used for non-quick-config price-set on 'Edit Contribution' form. I have fixed the js and here's how it looks now:

'Edit Contribution' with quick-config price-set:
screen shot 2018-07-03 at 12 02 12 pm

'Edit Contribution' with non-quick-config price-set:
test-multiple-after

**Comment by monishdeb** [comment]
> That said, this is looking very good compared to last week! I feel this is ready for the client to QA. I'll put it in front of them tomorrow, and hopefully we're in the final stretch on this.

Great. @MegaphoneJon after your approval, I will merge this PR and publish a new release 2.0 :)

**Comment by MegaphoneJon** [comment]
Unfortunately, this caused a regression and you can no longer add line items when creating a *new* contribution.

**Comment by monishdeb** [comment]
@MegaphoneJon  oops sorry about that. Fixed it now

**Comment by JoeMurray** [comment]
@monishdeb could you merge and publish a new release. Any further QA can be done on a new PR for a new release. Thx

**Comment by monishdeb** [comment]
Ok will do.

**Pull request merged**
