### PR TITLE
Prevent loss of line-item when multiple price field has same name

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by JoeMurray** [comment]
I think the possibility of a duplicate price field on name is present across different price sets but not possible for price fields within the same priceset iirc. Choosing the first one needs to changed to getting one from the correct price set, imho. Could you review how price fields names are validated on add and change? Thx.

**Comment by monishdeb** [comment]
Thanks Joe, for your feedback. I have corrected the patch by fetching priceFieldValue IDs based on right PriceSet name and is_quick_config flag, instead of priceFieldValue name. 

@seamuslee001 can you please review the PR?

**Comment by JoeMurray** [comment]
Good. I agree with this approach.

**Comment by seamuslee001** [comment]
I tested this and confirmed it works after I created a new Price field with the same name as the default one.  merging

**Review by seamuslee001 — APPROVED** [review]

**Pull request merged**
