### PR TITLE
github#39 add participant name on contribution edit page

### PR DESCRIPTION
**Pull request by samuelsov**
See https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/issues/39

Before :

Screenshot_2019-07-05 Edit Contribution - no participant name

After:

Screenshot_2019-07-05 Edit Contribution - with participant name

### CODE REVIEW

**Comment by monishdeb** [comment]
@samuelsov interesting change but my concern is, since its a general change and will affect other setups. There might not be a general agreement on this.  How about if we introduce a new hook  and via which you can modify the description without affecting the lineitemeditor?

**Comment by JoeMurray** [comment]
I am in favour of this change, but the name should be after rather than before the line item description. Let's rebase if necessary, test and merge.

**Comment by monishdeb** [comment]
Sorry @samuelsov for delay. Can you please append the display name after Line-item title as Joe suggested above?

**Comment by monishdeb** [comment]
I have updated PR rendering name after the line-item title. @seamuslee001 can you please review the patch?

**Comment by seamuslee001** [comment]
I tested the latest changes and I think we need to make an improvement because I notice the name shows up in the middle rather than after the price option label which seems confusing I think 
Name_line_item_middle

**Comment by JoeMurray** [comment]
Thanks, @seamuslee001 . Over to you, @monishdeb .

**Comment by monishdeb** [comment]
@seamuslee001 I have updated the PR and here's how it looks:
Screenshot 2021-02-10 at 6 27 45 AM


 Can you please check now?

**Comment by seamuslee001** [comment]
Looks good to me merging

**Pull request merged**
